/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import DataAccesObject.InterventionDAO;
import control.InterventionTableModel;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import model.Intervention;

/**
 *
 * @author lenovo
 */
public class AcceuilReception extends javax.swing.JPanel {

    /**
     * Creates new form AcceuilReception
     */
    public AcceuilReception() {
        initComponents();
        
        jTable2.setModel(new InterventionTableModel());
        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                jTable2.setModel(new InterventionTableModel(new InterventionDAO().getInterventionContainsChars(jTextField1.getText())));
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                jTable2.setModel(new InterventionTableModel(new InterventionDAO().getInterventionContainsChars(jTextField1.getText())));
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                jTable2.setModel(new InterventionTableModel(new InterventionDAO().getInterventionContainsChars(jTextField1.getText())));
            }
  
});
    }
    public AcceuilReception(String  service) {
        initComponents();
        jTextField1.setVisible(false);
        jLabel2.setVisible(false);
        
        jTable2.setModel(new InterventionTableModel(service));
        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                jTable2.setModel(new InterventionTableModel(new InterventionDAO().getInterventionContainsChars(jTextField1.getText())));
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                jTable2.setModel(new InterventionTableModel(new InterventionDAO().getInterventionContainsChars(jTextField1.getText())));
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                jTable2.setModel(new InterventionTableModel(new InterventionDAO().getInterventionContainsChars(jTextField1.getText())));
            }
  
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("Liste des intervention");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Chercher");

        jButton1.setText("OPERATION TERMINEE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(124, 124, 124)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 81, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int column = 0;
int row = jTable2.getSelectedRow();
String value = jTable2.getModel().getValueAt(row, column++).toString();
String value1 = jTable2.getModel().getValueAt(row, column++).toString();
String value2 = jTable2.getModel().getValueAt(row, column++).toString();
String value3 = jTable2.getModel().getValueAt(row, column++).toString();
String value4 = jTable2.getModel().getValueAt(row, column++).toString();
String value5 = jTable2.getModel().getValueAt(row, column++).toString();
String value6 = jTable2.getModel().getValueAt(row, column++).toString();
Intervention i=new Intervention(Integer.parseInt(value), Integer.parseInt(value1),Integer.parseInt( value2), value3, "termine", value5, value6);
new InterventionDAO().updateIntervention(i, i.getId());
InterventionTableModel tableModel = (InterventionTableModel) jTable2.getModel();
tableModel.fireTableDataChanged();

//jTable2.fireTableDataChanged();




repaint();
revalidate();
System.out.println("updated");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
